apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-classification
  labels:
    app: brand-classification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brand-classification
  template:
    metadata:
      labels:
        app: brand-classification
    spec:
      containers:
      - name: brand-classification
        image: wagnerrua/vehicle:brand-classification
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER
          value: "labic-kafka.default.svc.cluster.local:9092"
        - name: CUDA_VISIBLE_DEVICES
          value: "-1"
        - name: KAFKA_PRODUCER_TOPIC
          value: "event_bus"
        - name: KAFKA_CONSUMER_TOPIC
          value: "filtred_image"
        - name: KAFKA_CONSUMER_GROUP
          value: "brand_classification"
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"