apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-classification
  labels:
    app: brand-classification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brand-classification
  template:
    metadata:
      labels:
        app: brand-classification
    spec:
      containers:
      - name: brand-classification
        image: wagnerrua/vehicle:brand-classification
        imagePullPolicy: Always